version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: examen_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: express_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_NAME: examen_db
      DB_PORT: 3306
      PORT: 8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_front
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  mysql_data:
